Website Upgrade
hrhszsdtc/hrhszsdtc.github.io pull request #1
Opened 2023-08-15 09:26 UTC by ZeHangZhu

*写完了基本页面,但部分页面的数据待填充*

2023-08-15 10:02 UTC, hrh233 approved these changes
@CoderWharf

2023-08-15 10:44 UTC, CoderWharf approved these changes

2023-08-15 11:04 UTC, Glodtsual requested changes
请增加以下功能:
1. 最上方的"HRHSZSDTC"添加hrhszsdtc组织主页的链接<https://github.com/hrhszsdtc>并指定颜色为白色且颜色不变,打开方式为新窗口打开
2. 下方nav栏增加"社区页",链接指向<https://github.com/orgs/hrhszsdtc/discussions>,指定颜色黑色且不变,打开方式为新窗口打开

2023-08-15 11:05 UTC, ZeHangZhu commented
ok
















在 2023-08-15 19:04:39，"Glodtsual" ***@***.***> 写道：

@Glodtsual requested changes on this pull request.

请增加以下功能:

最上方的"HRHSZSDTC"添加hrhszsdtc组织主页的链接https://github.com/hrhszsdtc并指定颜色为白色且颜色不变,打开方式为新窗口打开
下方nav栏增加"社区页",链接指向https://github.com/orgs/hrhszsdtc/discussions,指定颜色黑色且不变,打开方式为新窗口打开

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-15 12:08 UTC, Glodtsual approved these changes

2023-08-15 12:08 UTC, hrh233 requested changes
请在增加新功能的同时保留我之前的更改,谢谢配合

2023-08-15 12:10 UTC, ZeHangZhu commented
sorry,之前没看到你修改了













在 2023-08-15 20:09:04，"hrh233" ***@***.***> 写道：

@hrh233 requested changes on this pull request.

请在增加新功能的同时保留我之前的更改,谢谢配合

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-21 05:21 UTC, hrh233 approved these changes

2023-08-21 05:23 UTC, merged